accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/',views.Register.as_view(), name='register' ),
    path('contact/',views.ContactView.as_view(), name='contact' ),
    path("firebase-config/", views.FirebaseConfig.as_view(), name="firebase-config"),
    path("firebase-login/", views.FirebaseLogin.as_view(), name="firebase-login"),
]

emuPDF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls"), name='accounts'),
    path('', include('pdf.urls'), name='pdf'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf/urls.py
from django.urls import path
from pdf.views.home_view import HomeView
from pdf.views.merge_view import MergeView
from pdf.views.split_view import SplitView
from pdf.views.lock_view import LockView
from pdf.views.unlock_view import UnlockView
from pdf.views.compress import CompressView
from pdf.views.pdf_to_word_view import PdfToWord
from pdf.views.convert_to_powerpoint_view import PdfToPowerpoint

app_name = 'pdf'
urlpatterns = [
    path('', HomeView.as_view(), name='home-view'),
    path('merge/', MergeView.as_view(), name='merge'),
    path('split/', SplitView.as_view(), name='split'),
    path('lock/', LockView.as_view(), name='lock'),
    path('unlock/', UnlockView.as_view(), name='unlock'),
    path('compress/', CompressView.as_view(), name='compress'),
    path('convert/', PdfToWord.as_view(), name='convert-to-word'),
    path('convert-to-powerpoint/', PdfToPowerpoint.as_view(), name='convert-to-powerpoint'),
]

templates/parts/carousel.html
<div class="carousel">

    <div class="slides">
        <!-- Hidden Radio Buttons -->
        <input type="radio" name="slide" id="s1" checked>
        <input type="radio" name="slide" id="s2">
        <input type="radio" name="slide" id="s3">
        <input type="radio" name="slide" id="s4">
        <input type="radio" name="slide" id="s5">
        <input type="radio" name="slide" id="s6">
        <input type="radio" name="slide" id="s7">

        <!-- Slide 1 -->
        <div class="slide slide1">
            <div class="content">
                <i class="icon">📄</i>
                <h2>Merge PDF</h2>
                <p>Combine multiple PDF files into one fast.</p>
                <a href="{% url 'pdf:merge' %}" class="btn">Start Merging</a>
            </div>
        </div>

        <!-- Slide 2 -->
        <div class="slide slide2">
            <div class="content">
                <!--                <i class="icon">🗜️</i>-->
                <i class="icon">✂️</i>
                <h2>Split PDF</h2>
                <p>Split PDF into equal sizes</p>
                <!--        <p>Reduce PDF size while staying sharp.</p>-->
                <a href="{% url 'pdf:split' %}" class="btn">Split Now</a>
            </div>
        </div>

        <!-- Slide 3 -->
        <div class="slide slide3">
            <div class="content">
                <i class="icon">🔒</i>
                <h2>Protect PDF</h2>
                <p>Encrypt PDFs with strong password security.</p>
                <a href="{% url 'pdf:lock' %}" class="btn">Secure PDF</a>
            </div>
        </div>
        <!-- Slide 6 -->
        <div class="slide slide6">
            <div class="content">
                <i class="icon">🔓</i>
                <h2>Unlock PDF</h2>
                <p>Remove password from a locked PDF.</p>
                <a href="{% url 'pdf:unlock' %}" class="btn">Unlock Now</a>
            </div>
        </div>
        <!-- Slide 4 -->
        <div class="slide slide4">
            <div class="content">
                <i class="icon">🗜️</i>
                <h2>Compress PDF</h2>
                <p>Reduce file size while maintaining quality.</p>
                <a href="{% url 'pdf:compress' %}" class="btn">Compress PDF</a>
            </div>
        </div>
        <!-- Slide 5 -->
        <div class="slide slide5">
            <div class="content">
                <i class="icon">📝</i>
                <h2>Convert PDF to Word</h2>
                <p>Convert PDF into fully editable Word files.</p>
                <a href="{% url 'pdf:convert-to-word' %}" class="btn">Convert PDF to Word</a>
            </div>
        </div>
        <!-- Slide 7 -->
        <div class="slide slide7">
            <div class="content">
                <i class="icon">📊</i>
                <h2>Convert to PowerPoint</h2>
                <p>Convert PDFs into presentation slides.</p>
                <a href="{% url 'pdf:convert-to-powerpoint' %}" class="btn">Convert to PowerPoint</a>
            </div>
        </div>
    </div>


    <!-- Dots -->
    <div class="navigation">
        <label for="s1" class="dot"></label>
        <label for="s2" class="dot"></label>
        <label for="s3" class="dot"></label>
        <label for="s4" class="dot"></label>
        <label for="s5" class="dot"></label>
        <label for="s6" class="dot"></label>
        <label for="s7" class="dot"></label>
    </div>

</div>

templates/parts/footer.html
<nav class="nav-footer">
    <div class="copyright">
        <p>&copy;emuPDF <span id="year"></span> — Convert • Merge • Protect</p>
        <script>document.getElementById("year").textContent = new Date().getFullYear();</script>
    </div>


</nav>

templates/parts/home_links.html
<div class="home-links">
    <a href="{% url 'pdf:merge' %}">Merge PDF</a>
    <a href="{% url 'pdf:split' %}">Split PDF</a>
    <a href="{% url 'pdf:lock' %}">Encrypt PDF</a>
    <a href="{% url 'pdf:unlock' %}">Unlock PDF</a>
    <a href="{% url 'pdf:compress' %}">Compress PDF</a>
    <a href="{% url 'pdf:convert-to-word' %}">Convert PDF to Word</a>
    <a href="{% url 'pdf:convert-to-powerpoint' %}">Convert PDF to PowerPoint</a>
</div>

templates/parts/navbar.html
{% load static %}
<nav class="navbar">
    <div class="nav-container">
        <a href="/" class="nav-logo">
            <img src="{% static 'pdf/logo/clogo.png' %}" alt="">
        </a>
        <ul class="nav-links">
            <li class="nav-link services">
                <div class="dropdown">
                    <a class="link" href="#">Services</a>
                    <div class="dropdown-options">
                        <a href="{% url 'pdf:merge' %}">Merge PDF</a>
                        <a href="{% url 'pdf:split' %}">Split PDF</a>
                        <a href="{% url 'pdf:lock' %}">Encrypt PDF</a>
                        <a href="{% url 'pdf:unlock' %}">Unlock PDF</a>
                        <a href="{% url 'pdf:compress' %}">Compress PDF</a>
                        <a href="{% url 'pdf:convert-to-word' %}">Convert PDF to Word</a>
                        <a href="{% url 'pdf:convert-to-powerpoint' %}">Convert PDF to PowerPoint</a>

                    </div>
                </div>
            </li>
            <li class="nav-link">
                <a class="link" href="{% url 'accounts:contact' %}">Contact</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-link">
                <form action="{% url 'accounts:logout' %}" method='post'>
                {% csrf_token %}
                <button class="logout-btn" type="submit" name='submit'>Log out</button>
            </form>
            </li>
            {% else %}
            <li class="nav-link">
                <a class="link" id="log-in" href="{% url 'accounts:login' %}">Log in</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>